name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install .[dev]
    - name: Generate Docs
      run: |
        make gen-docs
        touch docs/_build/html/.nojekyll
    - name: Publish Docs
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/_build/html/ # The folder the action should deploy.
